name: test
on:
  push:
    branches:
    - master
  pull_requests:
    branches:
    - master
  schedule:
  - cron: 0 0 * * *
jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
